---
extends:
  - "react-app"
  - "airbnb"

env:
  browser: true
  node: true
  es6: true
  jest: true

parser: "babel-eslint"

# 0: off, 1: warning, 2: error
rules:
  arrow-parens: [2, "as-needed"]
  quotes: [2, "single"]
  jsx-quotes: [2, "prefer-single"]
  indent: [2, 2]
  no-underscore-dangle: 0
  comma-style: [2, "last"]
  comma-dangle: ["error", {
    "arrays": "only-multiline",
    "objects": "only-multiline",
    "imports": "only-multiline",
    "exports": "only-multiline",
    "functions": "ignore",
  }]
  max-len: [2, 80, 1]
  no-console: 0
  arrow-body-style: 0
  no-confusing-arrow: 0
  react/prefer-stateless-function: 0
  react/jsx-wrap-multilines: 0
  react/forbid-prop-types: 0
  react/require-default-props: 0
  react/jsx-curly-spacing: 2
  react/jsx-indent-props: [2, 2]
  react/jsx-no-duplicate-props: 2
  react/no-danger: 2
  react/require-extension: 0
  react/prop-types: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  quote-props: 0
  import/extensions: 0
  generator-star-spacing: 0